[versions]
kotlin = "2.4.20"
compose = "1.12.1"
material3 = "1.9.0"
materialIcons = "1.7.3"
ktor = "3.6.0"
coroutines = "1.11.0"
serialization = "1.11.0"
innertubex = "v0.7.4"
coil = "3.6.3"
vlcj = "4.12.1"
protobuf = "4.36.2"
protobufPlugin = "0.10.0"
dbus = "5.2.2"

[libraries]
innertubex-desktop = { module = "com.github.MetrolistGroup.innertubex:innertubex-desktop", version.ref = "innertubex" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material-icons = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIcons" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
vlcj = { module = "uk.co.caprica:vlcj", version.ref = "vlcj" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobuf" }
protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
dbus-core = { module = "com.github.hypfvieh:dbus-java-core", version.ref = "dbus" }
dbus-transport = { module = "com.github.hypfvieh:dbus-java-transport-native-unixsocket", version.ref = "dbus" }
junit = { module = "junit:junit", version = "4.13.2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
